Repository clue/reactphp-mq, pull requests merged in 2018-02, with the labels that each got.

#2 Fixed variable name in README
  README.md
Labels: bug, maintenance

#3 Documentation for timeout handling
  README.md
Labels: easy pick, new feature

#4 Documentation and example for blocking integration
  README.md
  examples/11-http-blocking.php
Labels: new feature
